In [2]:
import numpy as np

In [6]:
'''Matrix Operation'''
a_2d_ist = [[11, 12, 13],[21, 22, 23]]
matrix_1 = np.array(a_2d_ist)
print(matrix_1)
print(matrix_1.shape)

a_2d_ist = [[1, 2, 3],[2, 2, 3]]
matrix_2 = np.array(a_2d_ist)
print(matrix_2)
print(matrix_2.shape)

[[11 12 13]
 [21 22 23]]
(2, 3)
[[1 2 3]
 [2 2 3]]
(2, 3)


In [4]:
#Scalar multiplication
var = 2
new_matrix = matrix_1*var
print(matrix_1)
print('New Matrix')
print(new_matrix)

[[11 12 13]
 [21 22 23]]
New Matrix
[[22 24 26]
 [42 44 46]]


In [5]:
#Matrix addition and SUbtraction 
new_matrix_add = matrix_1 + matrix_2
new_matrix_sub = matrix_1 - matrix_2

print('Matrix addition')
print(new_matrix_add)
print('Matrix Subtraction')
print(new_matrix_sub)

Matrix addition
[[12 14 16]
 [23 24 26]]
Matrix Subtraction
[[10 10 10]
 [19 20 20]]


In [7]:
#Matrix Transpose 
new_matrix_Transpose = matrix_1.T
print('Matrix 1')
print(matrix_1)
print('Matrix 1 .T')
print(new_matrix_Transpose)

Matrix 1
[[11 12 13]
 [21 22 23]]
Matrix 1 .T
[[11 21]
 [12 22]
 [13 23]]


In [9]:
#Matrix multiplication 
new_mat_mul = matrix_1.dot(matrix_2.T)
print(new_mat_mul)

[[ 74  85]
 [134 155]]


In [10]:
#Norm of a vector 
import math
a_vector = np.array([3, 4])
l2_norm = np.linalg.norm(a_vector, 2) #2 - power 2
print(l2_norm)

5.0


In [12]:
#Determinant of a matrix
matrix_new = np.array([[1, 2],[3, 4]])
det = np.linalg.det(matrix_new)
print(det)

-2.0000000000000004


In [13]:
#Inverse of a matrix
matrix_new = np.array([[1, 2],[3, 4]])
inv = np.linalg.inv(matrix_new)
print(inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [15]:
#Check orthogonal matrix
matrix_new = np.array([[1, 0],[0, -1]])
ortho_matrix = matrix_new.dot(matrix_new.T)
print(ortho_matrix)

[[1 0]
 [0 1]]


In [29]:
#LU decomposition 
import scipy.linalg as la
a_mat =np.array([[3, 4],[1, 2]])
print('a_mat')
print(a_mat)
P, L, U = la.lu(a_mat)
print('P')
print(P)
print('L')
print(L)
print('U')
print(U)

re_matrix = P.dot(L).dot(U)
print(re_matrix)

re_matrix_1 = L.dot(U)
print(re_matrix_1)

a_mat
[[3 4]
 [1 2]]
P
[[1. 0.]
 [0. 1.]]
L
[[1.         0.        ]
 [0.33333333 1.        ]]
U
[[3.         4.        ]
 [0.         0.66666667]]
[[3. 4.]
 [1. 2.]]
[[3. 4.]
 [1. 2.]]


In [32]:
#Eigen values and vectors
a_mat =np.array([[11, 12, 13],[21, 22, 23],[31, 32, 33]])
values, vectors = la.eig(a_mat)
print(values)
print(vectors)

[ 6.68969025e+01+0.j -8.96902513e-01+0.j  3.91097365e-15+0.j]
[[-0.29902183 -0.72775928  0.40824829]
 [-0.54214941 -0.02112604 -0.81649658]
 [-0.785277    0.6855072   0.40824829]]
